// Generated by CoffeeScript 1.3.3
(function() {
  var $, Backbone, FruitListView, FruitView, PojoListView, fruits, sortable, view,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PojoListView = require('../../index.js').PojoListView;

  Backbone = require('backbone');

  $ = require('jquery');

  Backbone.$ = $;

  fruits = ['apple', 'orange', 'banana'];

  sortable = 'sortable';

  FruitView = (function(_super) {

    __extends(FruitView, _super);

    function FruitView() {
      return FruitView.__super__.constructor.apply(this, arguments);
    }

    FruitView.prototype.render = function() {
      this.$el.html("<div>" + this.model + "</div>");
      this.$el.addClass('sortable');
      return this;
    };

    return FruitView;

  })(Backbone.View);

  FruitListView = (function(_super) {

    __extends(FruitListView, _super);

    function FruitListView() {
      return FruitListView.__super__.constructor.apply(this, arguments);
    }

    FruitListView.prototype.createItemView = function(item, index) {
      return new FruitView({
        model: item
      }).render();
    };

    return FruitListView;

  })(PojoListView);

  view = new FruitListView({
    model: fruits
  });

  view.render();

  $("body").append(view.el);

}).call(this);
